### ISSUE TITLE
Errors at compilation

### ISSUE THREAD

**Issue by Mauladen** [Wando1423/AimTux#21]
![Image](http://images.vfl.ru/ii/1494574100/482552b6/17195734.png)

**Comment by Wando1423** [comment]
Ok, try now. I think thats fixed.

**Comment by Mauladen** [comment]
![Image](http://images.vfl.ru/ii/1494575463/53bd16f1/17195886.png)

**Comment by Wando1423** [comment]
Try now. I have no possibility to compile it, so still might have some errors.

**Comment by Mauladen** [comment]
Everything went without errors
Thanks for the quick response 
Really liked your fork

**Comment by Wando1423** [comment]
Sure thing, post any issues if you'd have some more.

**Comment by Mauladen** [comment]
Again there are errors during compilation

![Image](http://i.imgur.com/QHRTH0u.png)
