### ISSUE TITLE
Again there are errors during compilation

### ISSUE THREAD

**Issue by Mauladen** [Wando1423/AimTux#23]
![Image](http://i.imgur.com/QHRTH0u.png)

**Comment by TiberiumN** [comment]
English version of this error:
![image](https://cloud.githubusercontent.com/assets/21169548/26026077/9600de12-37fd-11e7-87d9-7075ad28795b.png)

**Comment by TiberiumN** [comment]
@Wando1423 https://github.com/Wando1423/AimTux/pull/24

**Comment by Wando1423** [comment]
Fixed. Sorry, I was away.
